app = "zuvu-polymarket-agent"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  OPENAI_API_KEY = ""
  OPENAI_MODEL = "gpt-4-turbo-preview"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 